---@type { [string]:Type[] }
local types = {
    entities_with_energy_source = {
        'accumulator',
        'active-defense-equipment',
        'agricultural-tower',
        'ammo-turret',
        'arithmetic-combinator',
        'assembling-machine',
        'asteroid-collector',
        'battery-equipment',
        'beacon',
        'belt-immunity-equipment',
        'boiler',
        'burner-generator',
        'car',
        'crafting-machine',
        'decider-combinator',
        'electric-energy-interface',
        'electric-turret',
        'energy-shield-equipment',
        'furnace',
        'fusion-generator',
        'fusion-reactor',
        'generator',
        'generator-equipment',
        'inserter',
        'inventory-bonus-equipment',
        'lab',
        'lamp',
        'lightning-attractor',
        'loader',
        'loader-1x1',
        'locomotive',
        'mining-drill',
        'movement-bonus-equipment',
        'night-vision-equipment',
        'offshore-pump',
        'programmable-speaker',
        'pump',
        'radar',
        'reactor',
        'roboport',
        'roboport-equipment',
        'rocket-silo',
        'selector-combinator',
        'solar-panel',
        'solar-panel-equipment',
        'spider-vehicle',
    },

    military_effects = {
        'ammo-damage',
        'artillery-range',
        'gun-speed',
        'follower-robot-lifetime',
        'maximum-following-robots-count',
        'turret-attack',
    },

    military_entities = {
        'ammo-turret',
        'artillery-turret',
        'artillery-wagon',
        -- 'combat-robot', -- technically entities, it would be VERY tedious to remove their prototypes
        'electric-turret',
        'fluid-turret',
        'land-mine',
        -- 'turret',
        -- 'unit-spawner',
    },

    military_equipment = {
        'active-defense-equipment',
    },

    items = {
        'item',
        'ammo',
        'capsule',
        'gun',
        'item-with-entity-data',
        'item-with-label',
        'item-with-inventory',
        'blueprint-book',
        'item-with-tags',
        'selection-tool',
        'blueprint',
        'copy-paste-tool',
        'deconstruction-item',
        'spidertron-remote',
        'upgrade-item',
        'module',
        'rail-planner',
        'space-platform-starter-pack',
        'tool',
        'armor',
        'repair-tool',
    },

    vehicles = {
        'car',
        'spider-vehicle',
    },

}

return types